#!/usr/env/bash

count_git_changes() {
    git diff --numstat 2> /dev/null | wc -l
}

parse_git_branch() {
    CHANGES=$(count_git_changes)
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1 - '"$CHANGES"')/'
}

WHITE="\[\033[0m\]"
RED="\[\033[31m\]"
GREEN="\[\033[32m\]"
BLUE="\[\033[34m\]"
YELLOW="\[\033[33m\]"
CYAN="\[\033[36m\]"
GRAY="\[\033[90m\]"
MAGENTA="\[\033[35m\]"
LIGHT_MAGENTA="\[\033[95m\]"
LIGHT_BLUE="\[\033[94m\]"
LIGHT_GREEN="\[\033[92m\]"
LIGHT_GRAY="\[\033[37m\]"
LIGHT_CYAN="\[\033[96m\]"

 
# set the PS1 variable
PS1="\a$MAGENTA \A $CYAN \u $WHITE\w $YELLOW\$(parse_git_branch) $WHITE \$ "
