#!/usr/env/bash

function parseArguments {
    args=""
    for var in  "$@"
    do
      args="$args $var"
    done
    echo $args
}

function dcexec {
  args=$(parseArguments "$@")
  echo $args;
  docker-compose exec -T --user laradock workspace $args
}

function dcRequire {
  args=$(parseArguments "$@")
  dcexec composer require $args
}

function dartisan {
  base="php artisan"
  args=$(parseArguments "$@")
  docker-compose exec -T --user laradock workspace $base $args
}

function behat {
  args=$(parseArguments "$@")
  ./vendor/bin/behat $args --no-snippets
}

function gg {
  cd $projectPath
  if [ $# -ne 0 ]
    then
    for arg in $*
    do
      newDir=$(ls | grep $arg | sort | head -n 1)
      echo "Navigating to " $projectPath/$newDir
      cd $newDir
    done
  fi
}

function search {
  if [ $# -ne 0 ]
    then
    for arg in $*
    do
      newDir=$(find $projectPath/* -not -path '*/\.*' | grep $arg | grep -v "test" | sort)
    done
  fi
}

function vimConfig {
  vim  ~/.vimrc
}
function bashConfig {
  vim  ~/.profile
}
function sourceVim {
  source ~/.vimrc
}
function sourceBash {
  source ~/.profile
}

function metrics {
  phpmetrics --report-html=phpmetricsreport $*
}

function pubKey {
    cat ~/.ssh/id_rsa.pub | pbcopy
    echo "Copied public key to clipboard"
}

function addAlias {
   echo "alias $1=\"$2\"" >> $BASH_DIR/aliases
}
